--SCRIPTS NUEVOS A EJECUTAR EN EL ORACLE DE GCO:
 

-- EJECUTAR EN EL ESQUEMA DE TARJETAS:
--ALTER SESSION SET CURRENT_SCHEMA=TARJETAS;

CREATE TABLE TARJETAS."TTAR_CONCILIADOR_GEOPOS_HEAD"
(
	"ID"     					NUMBER(12,0) NOT NULL ENABLE,
	"FECHA_HORA_AUDITORIA"		TIMESTAMP NOT NULL ENABLE,
	"CDRAZONSOCIAL"				VARCHAR2(20 BYTE),
	"CDTIENDA"					VARCHAR2(20 BYTE),
	"FECHA_INICIAL"				VARCHAR2(10 BYTE),
	"FECHA_FINAL"				VARCHAR2(10 BYTE),
	"FORMA_PAGO"				VARCHAR2(20 BYTE),
	"MOSTRAR_SOLO_DIFERENCIA"	VARCHAR2(2 BYTE)
);

CREATE INDEX IX_CONCILIADOR_GEOPOS_HEAD_ID ON TARJETAS.TTAR_CONCILIADOR_GEOPOS_HEAD
("ID" ASC)
;

ALTER TABLE TARJETAS.TTAR_CONCILIADOR_GEOPOS_HEAD ADD CONSTRAINT PK_CONCILIADOR_GEOPOS_HEAD
	PRIMARY KEY ("ID") 
 USING INDEX 
;

GRANT ALL ON TARJETAS.TTAR_CONCILIADOR_GEOPOS_HEAD TO INVENTARIO;

CREATE SEQUENCE TARJETAS."SEQ_CONCILIADOR_GEOPOS_HEAD_ID" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;
GRANT ALL ON TARJETAS.SEQ_CONCILIADOR_GEOPOS_HEAD_ID TO INVENTARIO;

-------
-------
-------

CREATE TABLE TARJETAS."TTAR_CONCILIADOR_GEOPOS"
(
	"ID"     				NUMBER(12,0) NOT NULL ENABLE,
	"ID_HEAD"     			NUMBER(12,0) NOT NULL ENABLE,
	"FECHA_VENTA"			VARCHAR2(10 BYTE),
	"CDTIENDA"				VARCHAR2(20 BYTE),
	"NOMBRE_TIENDA"			VARCHAR2(150 BYTE),
	"NMCAJA"            	VARCHAR2(20 BYTE),
	"VALOR_TARJETAS"		NUMBER(20,2),
	"VALOR_GEOPOS"			NUMBER(20,2),
	"VALOR_DIFERENCIA"		NUMBER(20,2)
);

CREATE INDEX IX_TTAR_CONCILIADOR_GEOPOS_ID ON TARJETAS.TTAR_CONCILIADOR_GEOPOS
("ID" ASC)
;

ALTER TABLE TARJETAS.TTAR_CONCILIADOR_GEOPOS ADD CONSTRAINT PK_TTAR_CONCILIADOR_GEOPOS
	PRIMARY KEY ("ID") 
 USING INDEX 
;

ALTER TABLE TARJETAS.TTAR_CONCILIADOR_GEOPOS ADD CONSTRAINT FK1_TTAR_CONCILIADOR_GEOPOS
	FOREIGN KEY ("ID_HEAD") REFERENCES TARJETAS."TTAR_CONCILIADOR_GEOPOS_HEAD" ("ID") ENABLE
;


GRANT ALL ON TARJETAS.TTAR_CONCILIADOR_GEOPOS TO INVENTARIO;

CREATE SEQUENCE TARJETAS."SEQ_TTAR_CONCILIADOR_GEOPOS_ID" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;
GRANT ALL ON TARJETAS.SEQ_TTAR_CONCILIADOR_GEOPOS_ID TO INVENTARIO;


--COMMIT;