--SCRIPTS NUEVOS A EJECUTAR EN EL ORACLE DE GCO:
 

-- EJECUTAR EN EL ESQUEMA DE INVENTARIOS:
--ALTER SESSION SET CURRENT_SCHEMA=INVENTARIO;

ALTER TABLE INVENTARIO.TTAR_TIENDA ADD "NMRAZONSOCIAL_CONCILIADORGP" NUMBER(12,0) DEFAULT 4 NOT NULL ENABLE;

ALTER TABLE INVENTARIO.TTAR_TIENDA ADD CONSTRAINT FK03_TTAR_TIENDA
	FOREIGN KEY ("NMRAZONSOCIAL_CONCILIADORGP") REFERENCES INVENTARIO."TTAR_RAZONSOCIAL" ("NMRAZONSOCIAL") ENABLE
;

INSERT INTO INVENTARIO."TTAR_PARAMETROSISTEMA" (NMPARAMETROSISTEMA, CDPARAMETRO, DSPARAMETRO, DSVALOR, DSDESCRIPCION) VALUES ('57', 'EMAIL_CONCILIADOR_GP', 'EMAILS PARA NOTIFICAR RESULTADOS DEL CONCILIADOR DE TARJETAS VS GEOPOS', 'andresol@gco.com.co', 'EMAILS PARA NOTIFICAR RESULTADOS DEL CONCILIADOR DE TARJETAS VS GEOPOS');

--COMMIT;
